// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
// import SideNav from './components/sidenav';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
//           <div className="w-full flex-none md:w-64">
//             <SideNav />
//           </div>
//           <div className="flex-grow p-6 md:p-12 overflow-auto">{children}</div>
//         </div>
//       </body>
//     </html>
//   );
// }

import SideNav from './components/sidenav';

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="min-h-screen flex flex-col bg-gradient-to-b from-indigo-900 to-black text-white">
          <SideNav />
          <main className="flex-grow container mx-auto px-4 py-8">
            {children}
          </main>
          <footer className="bg-indigo-900 py-4 text-center">
            <p>© 2024 DreamScape. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
